#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := aquarium_monitor

EXTRA_COMPONENT_DIRS := /home/yra1029/esp/esp-idf-lib/components

 CFLAGS += -g

include $(IDF_PATH)/make/project.mk
